export const screens = {
  listing: "Listing",
  listingDetails: "Listing Details",
  home: "Home",
  listingEdit: "Listing Edit",
  account: "Accounts",
  welcome: "welcome",
  login: "Login",
  register: "Register",
  mMessage: "mMessage",
  mListing: "mListing",
  mAccount: "mAccount",
  messageDetail: "message detail",
  myListings: "my listings",
};
